### ISSUE TITLE
Remove user_email as a setting

### ISSUE THREAD

**Issue by phvntominc** [creativehassan/snap-pixel#1]
Passing the email of the account that owns the pixel is entirely wrong. The intended use of the user_email variable is to connect the conversions with the customer that is performing them. 

Read the documentation: [Install Pixel](https://businesshelp.snapchat.com/en-US/a/pixel-website-install#InstallPixel)

With this setup, every desirable action is attributed to the same person: the advertiser. It also prevents Snapchat from learning the audience because none of the actions are attributed to the email that's actually performing them. The whole point of the pixel is to retarget users on Snapchat who have demonstrated interest by visiting the website. This will cause Snapchat to just retarget the advertiser.

Thus, this can't be a setting because it's a dynamic value. It's an easy fix inside the pixel snippet:

```
<?php 

$user = wp_get_current_user(); ?>
snaptr('init','<?php echo $this->pixel_id; ?>',{
			 <?php if( 0 < $user->ID ) ?> 'user_email':'<?php echo $user->user_email; ?>'
			})
```

**Comment by creativehassan** [comment]
@phvntominc, 

Thank you for notifying me I have updated the plugin on the repository kindly update the plugin. 

Thanks
