### ISSUE TITLE
Fatal error if woocommerce is not installed

### ISSUE THREAD

**Issue by martinkolle** [creativehassan/snap-pixel#2]
>  Fatal error: Uncaught Error: Call to undefined function wc_get_product() in /public_html/wp-content/plugins/snap-pixel/includes/function.php:112

A easy fix will be to check if woocommerce is installed on line 112 in `snapchat_pixel_code_everywhere()`
``if( $this->snapchat_pixel_wooexist() ) {
	$_product = wc_get_product($product_id);
	if( $post && $_product && is_product() ){
		$producted_id = $_product->get_id();
	}
}``

**Comment by creativehassan** [comment]
Hi @martinkolle, 

You can get the updated code from WordPress repo. 
https://wordpress.org/plugins/snap-pixel/

Thanks

**Comment by creativehassan** [comment]
I will update the GitHub repo soon as well.

**Comment by martinkolle** [comment]
We are using the latest version from Wordpress Plugins

**Comment by creativehassan** [comment]
Ah okay, can you send me link where you are getting this error, please? 

Thanks

**Comment by creativehassan** [comment]
@martinkolle, 

Thank you so much for noticing I have removed this fatal error and updated on WordPress repo. Please update the plugin. 

Thanks

**Comment by martinkolle** [comment]
You are welcome. Thanks for a nice plugin! Enjoy your day.
